apiVersion: apps.kristian.io/v1alpha1
kind: KristianApp
metadata:
  name: myapp
  namespace: myapp-dev
spec:
  image: gcr.io/google-samples/hello-app:1.0
  environment: dev
  autoscaling:
    enable: true
    maxReplicas: 5
    minReplicas: 3
  ingress:
    enable: false
