apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysecondapp
  namespace: mysecondapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysecondapp
  template:
    metadata:
      labels:
        app: mysecondapp
    spec:
      containers:
      - name: mysecondapp
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
