apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-app
  namespace: my-second-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-second-app
  template:
    metadata:
      labels:
        app: my-second-app
    spec:
      containers:
      - name: my-second-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
